### ISSUE TITLE
Not able to create delivery note showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#777] opened 2024-11-29 08:53 UTC
### Information about bug

![image](https://github.com/user-attachments/assets/fe2ae117-cf90-429d-8aa5-aee5c754123d)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Delivery Note/new-delivery-note-relyugdiai
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
    set_name_by_naming_series(doc)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
  File "apps/frappe/frappe/model/naming.py", line 271, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
  File "apps/frappe/frappe/model/naming.py", line 71, in generate_next_name
    return parse_naming_series(parts, doc=doc)
  File "apps/frappe/frappe/model/naming.py", line 329, in parse_naming_series
    part = number_generator(name, digits)
  File "apps/frappe/frappe/model/naming.py", line 381, in getseries
    current = (frappe.qb.from_(series).where(series.name == key).for_update().select("current")).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Delivery Note\",\"name\":\"new-delivery-note-relyugdiai\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"MAT-DN-.YYYY.-\",\"posting_date\":\"2024-11-29\",\"set_posting_time\":0,\"company\":\"PP Ltd\",\"is_return\":0,\"issue_credit_note\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Delivery Note Item\",\"name\":\"new-delivery-note-item-ejanojuwcx\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"has_item_scanned\":0,\"item_group\":\"_Test Item Group\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"allow_zero_valuation_rate\":0,\"use_serial_batch_fields\":1,\"packed_qty\":0,\"cost_center\":\"Main - PP Ltd\",\"page_break\":0,\"parent\":\"new-delivery-note-relyugdiai\",\"parentfield\":\"items\",\"parenttype\":\"Delivery Note\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"returned_qty\":0,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":3000,\"amount\":3000,\"base_rate\":3000,\"base_amount\":3000,\"stock_uom_rate\":3000,\"net_rate\":3000,\"net_amount\":3000,\"base_net_rate\":3000,\"base_net_amount\":3000,\"billed_amt\":0,\"incoming_rate\":0,\"weight_per_unit\":0,\"total_weight\":0,\"actual_batch_qty\":0,\"actual_qty\":3711,\"installed_qty\":0,\"received_qty\":0,\"warehouse\":\"Stores - PP Ltd\",\"item_code\":\"CPU\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"CPU\",\"description\":\"CPU\",\"image\":\"\",\"income_account\":\"Sales - PP Ltd\",\"expense_account\":\"Cost of Goods Sold - PP Ltd\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"update_stock\":0,\"delivered_by_supplier\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-11-29\",\"against_blanket_order\":null,\"bom_no\":null,\"is_fixed_asset\":0,\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"projected_qty\":3517,\"reserved_qty\":205,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-delivery-note-item-ejanojuwcx\"}],\"taxes\":[],\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"packed_items\":[],\"pricing_rules\":[],\"status\":\"Draft\",\"lr_date\":\"2024-11-29\",\"sales_team\":[],\"print_without_amount\":0,\"group_same_items\":0,\"is_internal_customer\":0,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"posting_time\":\"14:12:30\",\"conversion_rate\":1,\"plc_conversion_rate\":1,\"letter_head\":\"PP Ltd\",\"base_net_total\":3000,\"net_total\":3000,\"base_total\":3000,\"total\":3000,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":3000,\"base_grand_total\":3000,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":3000,\"base_rounded_total\":3000,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"amount_eligible_for_commission\":3000,\"total_commission\":null,\"tax_id\":null,\"customer_name\":\"Ashish\",\"represents_company\":null,\"customer\":\"Ashish\",\"customer_address\":\"Pune East-Shipping\",\"address_display\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"shipping_address_name\":\"Pune East-Shipping\",\"shipping_address\":\"Pune<br>\\nPune<br>\\nIndia<br>\\n<br>\\n\",\"company_address\":\"PP-MH-Billing\",\"company_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"tax_category\":\"In-State\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"set_warehouse\":\"Stores - PP Ltd\",\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370046808907294434631": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4143,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SerializationFailure",
	"_debug_messages": "[\"Error in query:\\ncould not serialize access due to concurrent update\\n\"]"
}
```
```

**Comment by shubham-DT** [comment] 2024-12-02 08:02
This issue is working fine 
we can close it

**Comment by IamSaiyyamChhetri** [comment] 2024-12-09 07:17
Not Able to reproduce this issue.

**Comment by aasif-patel** [comment] 2024-12-30 06:47
Completed hance close

**Closed as completed by aasif-patel** 2024-12-30 06:47 UTC
Labels: bug, Delivery Note, concurrent update
