### ISSUE TITLE
Material Request: While access the link Supplier Quotation through Material request Connection Tab getting Server error

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#48] opened 2024-09-26 07:36 UTC
### Information about bug

Material Request-> Connections -> Supplier Quotation -> view the linked quotation getting error
![image](https://github.com/user-attachments/assets/d689cd44-c0a9-4c38-a10d-2b593eaffb01)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
List/Supplier Quotation/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 928, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 69, in get_count
    count = frappe.db.sql(f"""select count(*) from ( {partial_query} ) p""")[0][0]
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "distinct"
LINE 1: select count(*) from ( select distinct distinct cast("tabSup...
                                               ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Supplier Quotation",
		"filters": "[[\"Supplier Quotation Item\",\"material_request\",\"=\",\"MAT-MR-2024-00004\"]]",
		"fields": "[]",
		"distinct": true,
		"limit": 1001
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_debug_messages": "[\"Syntax error in query:\\nselect count(*) from ( select distinct distinct cast(\\\"tabSupplier Quotation\\\".name as varchar)\\n\\t\\t\\tfrom \\\"tabSupplier Quotation\\\" left join \\\"tabSupplier Quotation Item\\\" on (\\\"tabSupplier Quotation Item\\\".parenttype = 'Supplier Quotation' and \\\"tabSupplier Quotation Item\\\".parent = cast(\\\"tabSupplier Quotation\\\".name as varchar))\\n\\t\\t\\twhere \\\"tabSupplier Quotation Item\\\".\\\"material_request\\\" = 'MAT-MR-2024-00004'\\n\\t\\t\\t\\n\\t\\t\\t\\n\\t\\t\\tlimit 1001 offset 0 ) p \"]"
}
```
```

**Comment by VishvParikh** [comment] 2024-09-30 07:20
@8848swa and @aasif-patel 
i didn't find issue issue in supplier quotation 
please check it it is already resolved

**Comment by aasif-patel** [comment] 2024-09-30 10:26
![image](https://github.com/user-attachments/assets/46ed37bb-52a6-4148-8c41-b20bd577391b)
Accessing linked Doctype from connection tab
Not just Supplier Quotation, Request for Quotation and Purchase Order All showing same error, @VishvParikh please check

**Comment by aasif-patel** [comment] 2024-10-01 07:13
Frappe Side changes, Needs to check

**Comment by aasif-patel** [comment] 2024-10-01 10:10
Issue caused by same query https://github.com/8848digital/erpnext/issues/96

**Comment by aasif-patel** [comment] 2024-10-04 13:18
@VishvParikh this may resolve the issue. something wrong with get_all api.

![image](https://github.com/user-attachments/assets/25601203-48b0-48d6-8bf3-50d0276ab9bd)

**Comment by aasif-patel** [comment] 2024-10-07 12:15
Resolved hence closing...

**Closed as completed by aasif-patel** 2024-10-07 12:15 UTC
Labels: bug, Supplier Quotation, On Hold
