### ISSUE TITLE
Serial No Warranty Expiry:Invalid filter: delivery_document_type

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#13] opened 2024-09-19 09:51 UTC
### Information about bug

click show report , showing an error 
Invalid filter: delivery_document_type
![Screenshot from 2024-09-19 15-14-52](https://github.com/user-attachments/assets/42e3a753-c65d-4e19-8e36-e426bfa17a59)

### Module

stock

### Version

Frappe version-15
ERPNext version-15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Invalid filter: delivery_document_type
```

**Comment by VishvParikh** [comment] 2024-09-26 07:56
@aasif-patel the problem is solved please check it

**Comment by aasif-patel** [comment] 2024-09-26 09:20
Resolved, Hence Closing...

**Closed as completed by aasif-patel** 2024-09-26 09:20 UTC
Labels: bug
